# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-04 17:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='citydict',
            old_name='description',
            new_name='desc',
        ),
    ]
